package com.android.speedsearch.ui;

import com.android.speedsearch.R;

import android.app.Application;
import android.graphics.Bitmap;
import android.os.Bundle;

public class speedsearchItem extends Application{
  public static String API_NUMBER = "72ae1cdfd83b7f5e";
  public static String COMPANY_CODE = "";
  public static String EXP_NO = "";
  public static Bitmap Bitmapcodebar;
  public static String Barcodeformat = "";
  public static String barcodetype = "";
  public static String URL = "http://api.kuaidi100.com/api?id={0}&com={1}&nu={2}&show=0&muti=1&order=desc";
  public static String[] code = {
	  	"ems",
	    "shentong",
	    "shunfeng",
	    "tiantian",
	    "yuantong",
	    "zhaijisong",
	    "zhongtong",
	    "anjiekuaidi",
	    "anxindakuaixi",
	    "baifudongfang",
	    "biaojikuaidi",
	    "bht",
	    "cces",
	    "coe",
	    "changyuwuliu",
	    "datianwuliu",
	    "debangwuliu",
	    "dpex",
	    "dhl",
	    "dsukuaidi",
	    "fedex",
	    "feikangda",
	    "fenghuangkuaidi",
	    "ganzhongnengda",
	    "guangdongyouzhengwuliu",
	    "gls",
	    "huitongkuaidi",
	    "hengluwuliu",
	    "huaxialongwuliu",
	    "jinguangsudikuaijian",
	    "jixianda",
	    "jiajiwuliu",
	    "jiayiwuliu",
	    "jiayunmeiwuliu",
	    "kuaijiesudi",
	    "lianhaowuliu",
	    "longbanwuliu",
	    "lanbiaokuaidi",
	    "minghangkuaidi",
	    "peisihuoyunkuaidi",
	    "quanchenkuaidi",
	    "quanjitong",
	    "quanritongkuaidi",
	    "quanyikuaidi",
	    "shenghuiwuliu",
	    "suer",
	    "shengfengwuliu",
	    "shangda",
	    "tiandihuayu",
	    "tnt",
	    "ups",
	    "wanjiawuliu",
	    "wenjiesudi",
	    "wuyuansudi",
	    "wanxiangwuliu",
	    "xinbangwuliu",
	    "xinfengwuliu",
	    "xingchengjibian",
	    "xinhongyukuaidi",
	    "yafengsudi",
	    "yibangwuliu",
	    "youshuwuliu",
	    "yuanchengwuliu",
	    "yuanweifeng",
	    "yuanzhijiecheng",
	    "yuefengwuliu",
	    "yunda",
	    "yuananda",
	    "yuanfeihangwuliu",
	    "yuntongkuaidi",
	    "zhongtiewuliu",
	    "zhongyouwuliu"
  };
  public static int[] more_image = {
	  R.drawable.more_bookmark,
	  R.drawable.more_quit
  };
  public static String[] name = {    
	  	"EMS(e邮宝)",
	    "申通",
	    "顺丰速运",
	    "天天",
	    "圆通",
	    "宅急送",
	    "中通速递",
	    "安捷快递",
	    "安信达快递",
	    "百福东方",
	    "彪记快递",
	    "BHT",
	    "希伊艾斯快递",
	    "中国东方(COE)",
	    "长宇物流",
	    "大田物流",
	    "德邦物流",
	    "DPEX",
	    "DHL",
	    "D速快递",
	    "fedex",
	    "飞康达物流",
	    "凤凰快递",
	    "港中能达物流",
	    "广东邮政物流",
	    "GLS快递",
	    "港中能达物流",
	    "广东邮政物流",
	    "GLS快递",
	    "京广速递",
	    "急先达",
	    "佳吉物流",
	    "佳怡物流",
	    "加运美",
	    "快捷速递",
	    "联昊通物流",
	    "龙邦物流",
	    "蓝镖快递",
	    "民航快递",
	    "配思货运",
	    "全晨快递",
	    "全际通物流",
	    "全日通快递",
	    "全一快递",
	    "盛辉物流",
	    "速尔物流",
	    "盛丰物流",
	    "上大物流",
	    "天地华宇",
	    "TNT",
	    "UPS",
	    "万家物流",
	    "文捷航空速递",
	    "伍圆速递",
	    "万象物流",
	    "新邦物流",
	    "信丰物流",
	    "星晨急便",
	    "鑫飞鸿物流",
	    "亚风速递",
	    "一邦速递",
	    "优速物流",
	    "远成物流",
	    "源伟丰快递",
	    "元智捷诚快递",
	    "越丰物流",
	    "韵达快运",
	    "源安达",
	    "原飞航物流",
	    "运通快递",
	    "中铁快运",
	    "中邮物流"
  };

  public void onCreate(Bundle savedInstanceState){
  }
}